# Generated by Django 3.0.14 on 2023-11-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0004_auto_20231106_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='url',
            field=models.URLField(),
        ),
    ]
