# Generated by Django 3.0.14 on 2023-11-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0005_auto_20231106_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapeddata',
            name='url',
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='picture',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
