# Generated by Django 3.0.14 on 2023-11-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0010_parseddata_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseddata',
            name='website',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
