# Generated by Django 3.0.14 on 2023-11-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0014_market_reviewrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='new_price',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='old_price',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
