# Generated by Django 4.2.7 on 2023-12-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0017_market_photo_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pizza',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
