# Generated by Django 4.2.7 on 2023-12-05 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0018_market_category_pizza_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pizza',
            new_name='Pizzaroni',
        ),
        migrations.RenameModel(
            old_name='Market',
            new_name='Wildberries',
        ),
    ]
