# Generated by Django 4.2.7 on 2023-12-31 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0019_rename_pizza_pizzaroni_rename_market_wildberries'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='product',
            index_together=None,
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RenameField(
            model_name='wildberries',
            old_name='new_price',
            new_name='price',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
