# Generated by Django 4.2.7 on 2024-01-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0020_alter_product_index_together_remove_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wildberries',
            old_name='product_id',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='pizzaroni',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pizzaroni',
            name='url',
        ),
        migrations.RemoveField(
            model_name='wildberries',
            name='category',
        ),
        migrations.AddField(
            model_name='pizzaroni',
            name='old_price',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
