# Generated by Django 4.2.7 on 2024-01-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='old_price',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
