# Generated by Django 3.0.14 on 2023-11-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0003_scrapeddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
