# Generated by Django 3.0.14 on 2023-11-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0006_auto_20231112_0308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapeddata',
            name='description',
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
