# Generated by Django 3.0.14 on 2023-11-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0007_auto_20231112_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('picture_url', models.URLField()),
                ('url', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='ScrapedData',
        ),
    ]
