# Generated by Django 3.0.14 on 2023-11-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0008_auto_20231115_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseddata',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
