# Generated by Django 3.0.14 on 2023-11-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0012_auto_20231116_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('product_id', models.SlugField(max_length=200, null=True)),
                ('picture_urls', models.URLField(null=True)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
